FROM python:3.10-slim

WORKDIR /Great_docker_env

COPY ./requirments.txt ./
RUN pip install --nocache-dir -r requirments.txt

COPY  ./Great_docker_env/src ./src

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]

